name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    tags: ["**"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      path_name: ${{ steps.refname.outputs.path_name }}
      artifact_name: ${{ steps.refname.outputs.artifact_name }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --fund=false

      - name: Compute path/ref names
        id: refname
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            REF="${{ github.head_ref }}"
          else
            REF="${{ github.ref_name }}"
          fi

          ARTIFACT_NAME="${REF//\//-}"

          echo "Output: $GITHUB_OUTPUT"
          echo "Ref: $RE)"
          echo "Path: $(basename $REF)"
          echo "Artifact: $ARTIFACT_NAME"

          echo "path_name=$(basename $REF)" >> "$GITHUB_OUTPUT"
          echo "artifact_name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

      - name: Prepare site
        run: |
          sed -i 's/\(<title>\).*\(<\/title>\)/\1Preview ${{ steps.refname.outputs.path_name }}\2/' src/index.html

      - name: Build site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.refname.outputs.artifact_name }}
          path: www/
          if-no-files-found: error
          overwrite: true

  #! Doesnt work on forked PRs
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Prepare directory
        run: |
          mkdir -p ${{ needs.build.outputs.path_name }}
          rm -rf "${{ needs.build.outputs.path_name }}/*"

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: ${{ needs.build.outputs.path_name }}

      - name: Commit & push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "[ci] update deployment for ${{ needs.build.outputs.path_name}}"
          git push

      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: ${{ needs.build.outputs.path_name }}-preview-comment
          message: |
            **🖥️ Preview**

            This PR can be previewed [here](https://definitelynotsimon13.github.io/webeng2/${{ needs.build.outputs.path_name }}).
